//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QCMS_BUSSINESS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChuyenXe
    {
        public int MaChuyenXe { get; set; }
        public Nullable<System.DateTime> Ngaydi { get; set; }
        public Nullable<System.DateTime> Giokhoihanh { get; set; }
        public Nullable<System.TimeSpan> Thoigiandukien { get; set; }
        public Nullable<int> MaXe { get; set; }
        public string Mota { get; set; }
        public string Chitiet { get; set; }
        public Nullable<int> TuyenDuong { get; set; }
        public string Diemdi { get; set; }
        public string Diemden { get; set; }
        public Nullable<int> TrangThai { get; set; }
        public Nullable<double> GiaVIP { get; set; }
        public Nullable<double> GiaThuong { get; set; }
        public Nullable<int> TongVe { get; set; }
        public Nullable<int> VeThuongConLai { get; set; }
        public string SDT { get; set; }
        public Nullable<int> KhuyenMai { get; set; }
        public string LoTrinh { get; set; }
        public string url { get; set; }
        public Nullable<int> TongSoVeVIP { get; set; }
        public Nullable<int> TongSoVeThuong { get; set; }
        public Nullable<int> VeVipConLai { get; set; }
        public Nullable<int> DenHuyen { get; set; }
        public Nullable<int> DenTinh { get; set; }
        public Nullable<int> DiHuyen { get; set; }
        public Nullable<int> DiTinh { get; set; }
    
        public virtual Xe Xe { get; set; }
    }
}
