//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QCMS_BUSSINESS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Code
    {
        public int ID { get; set; }
        public string TABLE_NAME { get; set; }
        public string TYPE { get; set; }
        public Nullable<int> TABLE_PK { get; set; }
        public string CODE1 { get; set; }
        public string VALUE { get; set; }
        public string MOTA { get; set; }
    }
}
