//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QCMS_BUSSINESS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diadiem
    {
        public int ID { get; set; }
        public string TenDiaDiem { get; set; }
        public Nullable<int> MaHuyen { get; set; }
    
        public virtual QuanHuyen QuanHuyen { get; set; }
    }
}
