//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QCMS_BUSSINESS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ghe
    {
        public int ID { get; set; }
        public Nullable<int> Maxe { get; set; }
        public Nullable<int> Tang { get; set; }
        public Nullable<int> Hang { get; set; }
        public Nullable<int> Cot { get; set; }
        public Nullable<int> Trangthai { get; set; }
        public string Loai { get; set; }
    
        public virtual Xe Xe { get; set; }
    }
}
