//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QCMS_BUSSINESS
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiaoDich
    {
        public int ID { get; set; }
        public string MaGiaoDich { get; set; }
        public Nullable<System.DateTime> ThoiGianGiaoDich { get; set; }
        public Nullable<double> GiaTriGiaoDich { get; set; }
        public string DauMoiGiaoDich { get; set; }
        public string MaTheGiaoDich { get; set; }
        public Nullable<int> MemberID { get; set; }
        public Nullable<int> TrangThaiGiaoDich { get; set; }
    }
}
