//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QCMS_BUSSINESS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModBtn
    {
        public int Btn_ID { get; set; }
        public string Btn_Name { get; set; }
        public string Btn_ExecuteSP { get; set; }
        public Nullable<bool> Btn_isExec { get; set; }
        public Nullable<int> ModID { get; set; }
        public Nullable<int> Btn_Type { get; set; }
        public string Btn_JsFunc { get; set; }
        public string Btn_NetFunc { get; set; }
        public Nullable<bool> isConfirm { get; set; }
        public string ConfirmContent { get; set; }
        public Nullable<bool> AlertAfterExec { get; set; }
        public string AlertContent { get; set; }
        public string Btn_faIcon { get; set; }
        public string Btn_BootstrapClass { get; set; }
        public string act { get; set; }
    }
}
