//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QCMS_BUSSINESS
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhaXe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhaXe()
        {
            this.Xes = new HashSet<Xe>();
            this.tbl_User = new HashSet<tbl_User>();
        }
    
        public int ID { get; set; }
        public string Tennhaxe { get; set; }
        public Nullable<int> Soluongxe { get; set; }
        public string Trusochinh { get; set; }
        public string Nguoidaidien { get; set; }
        public string Sodienthoai { get; set; }
        public string Gioithieungan { get; set; }
        public string Gioithieuchitiet { get; set; }
        public string Anh { get; set; }
        public Nullable<int> Tinh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Xe> Xes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_User> tbl_User { get; set; }
    }
}
