//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QCMS_BUSSINESS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ModAdmin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_ModAdmin()
        {
            this.ModFLDs = new HashSet<ModFLD>();
            this.tbl_User = new HashSet<tbl_User>();
        }
    
        public int ModAdmin_ID { get; set; }
        public Nullable<int> ModAdmin_Parent { get; set; }
        public string ModAdmin_Name { get; set; }
        public string ModAdmin_Path { get; set; }
        public string ModAdmin_Icon { get; set; }
        public string ModAdmin_Info { get; set; }
        public Nullable<bool> ModAdmin_Status { get; set; }
        public Nullable<int> ModAdmin_Pos { get; set; }
        public string Onload { get; set; }
        public string OnSelect { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ModFLD> ModFLDs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_User> tbl_User { get; set; }
    }
}
