//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QCMS_BUSSINESS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Member
    {
        public int Member_ID { get; set; }
        public string Member_Username { get; set; }
        public string Member_Email { get; set; }
        public string Member_Password { get; set; }
        public string Member_Name { get; set; }
        public string Member_SurName { get; set; }
        public string Member_LastName { get; set; }
        public string Member_Sex { get; set; }
        public string Member_Address { get; set; }
        public string Member_Phone { get; set; }
        public string Member_Mobile { get; set; }
        public string Member_Company { get; set; }
        public Nullable<bool> Member_Status { get; set; }
        public Nullable<System.DateTime> Member_Date { get; set; }
        public string Member_Avarta { get; set; }
        public Nullable<long> Member_Vola { get; set; }
    }
}
