//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QCMS_BUSSINESS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Comment
    {
        public int Comment_ID { get; set; }
        public Nullable<int> Content_ID { get; set; }
        public string Comment_Name { get; set; }
        public string Comment_Content { get; set; }
        public Nullable<bool> Comment_Status { get; set; }
        public Nullable<System.DateTime> Comment_Date { get; set; }
        public string Comment_FullName { get; set; }
        public string Comment_Email { get; set; }
        public string Comment_Address { get; set; }
        public string Comment_Tel { get; set; }
        public Nullable<int> Comment_Pos { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> OverallRating { get; set; }
        public Nullable<int> QualityRating { get; set; }
        public Nullable<int> OnTimeRating { get; set; }
        public Nullable<int> ServiceRating { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> RatingAverage { get; set; }
    }
}
