//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QCMS_BUSSINESS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Content
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Content()
        {
            this.tbl_Comment = new HashSet<tbl_Comment>();
            this.tbl_File = new HashSet<tbl_File>();
        }
    
        public int Content_ID { get; set; }
        public Nullable<int> Mod_ID { get; set; }
        public Nullable<int> User_ID { get; set; }
        public Nullable<int> Hang_ID { get; set; }
        public string Content_Name { get; set; }
        public string Content_Code { get; set; }
        public Nullable<System.DateTime> Content_Editdate { get; set; }
        public string Content_Title { get; set; }
        public string Content_Key { get; set; }
        public string Content_Des { get; set; }
        public string Content_Tag { get; set; }
        public string Content_UrlTags { get; set; }
        public string Content_Price { get; set; }
        public string Content_Img { get; set; }
        public string Content_Avata { get; set; }
        public string Content_URL { get; set; }
        public string Content_Intro { get; set; }
        public string Content_Text { get; set; }
        public Nullable<System.DateTime> Content_Date { get; set; }
        public Nullable<int> Content_Count { get; set; }
        public Nullable<bool> Content_Status { get; set; }
        public Nullable<bool> Content_Hot { get; set; }
        public Nullable<bool> Content_Home { get; set; }
        public Nullable<int> Content_Pos { get; set; }
        public Nullable<int> lang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Comment> tbl_Comment { get; set; }
        public virtual tbl_Mod tbl_Mod { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_File> tbl_File { get; set; }
    }
}
