//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QCMS_BUSSINESS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Tag
    {
        public int Tag_ID { get; set; }
        public Nullable<int> Content_ID { get; set; }
        public string Tag_Name { get; set; }
        public string Tag_Url { get; set; }
        public Nullable<int> Tag_Count { get; set; }
    }
}
