//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QCMS_BUSSINESS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PromoteCode
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public Nullable<double> ValueCast { get; set; }
        public Nullable<int> ValuePercent { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> isDelete { get; set; }
        public Nullable<double> FromValue { get; set; }
        public Nullable<double> ToValue { get; set; }
        public Nullable<bool> isPercent { get; set; }
        public string Unit { get; set; }
    }
}
