//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QCMS_BUSSINESS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Config
    {
        public int Config_ID { get; set; }
        public string Config_Name { get; set; }
        public string Config_Values { get; set; }
        public string Config_Code { get; set; }
        public Nullable<bool> Config_Status { get; set; }
    }
}
