//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QCMS_BUSSINESS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Skintype
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Skintype()
        {
            this.tbl_Skin = new HashSet<tbl_Skin>();
        }
    
        public int Skintype_ID { get; set; }
        public string Skintype_Name { get; set; }
        public string Skintype_Code { get; set; }
        public string Skintype_Target { get; set; }
        public Nullable<bool> Skintype_Viewtype { get; set; }
        public Nullable<int> Skintype_Limit { get; set; }
        public Nullable<int> Skintype_Width { get; set; }
        public Nullable<int> Skintype_Height { get; set; }
        public Nullable<int> Skintype_Vspace { get; set; }
        public Nullable<int> Skintype_Hspace { get; set; }
        public Nullable<bool> Skintype_Status { get; set; }
        public Nullable<int> Skintype_Pos { get; set; }
        public Nullable<int> lang { get; set; }
        public Nullable<int> Skintype_Parent { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Skin> tbl_Skin { get; set; }
    }
}
