//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QCMS_BUSSINESS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Other
    {
        public int Other_ID { get; set; }
        public string Other_Mod { get; set; }
        public string Other_Name { get; set; }
        public string Other_Content { get; set; }
        public Nullable<bool> Other_Status { get; set; }
        public Nullable<int> lang { get; set; }
    }
}
