//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QCMS_BUSSINESS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_User()
        {
            this.tbl_RoleUser = new HashSet<tbl_RoleUser>();
            this.tbl_Mess = new HashSet<tbl_Mess>();
            this.tbl_Mod = new HashSet<tbl_Mod>();
            this.tbl_ModAdmin = new HashSet<tbl_ModAdmin>();
        }
    
        public int User_ID { get; set; }
        public string username { get; set; }
        public string User_Pass { get; set; }
        public Nullable<int> pb_ID { get; set; }
        public string User_Email { get; set; }
        public string User_Yahoo { get; set; }
        public string User_Name { get; set; }
        public Nullable<bool> User_Sex { get; set; }
        public string User_Tel { get; set; }
        public string User_Mobile { get; set; }
        public string User_Address { get; set; }
        public string User_Img { get; set; }
        public string User_Info { get; set; }
        public Nullable<bool> User_Status { get; set; }
        public Nullable<bool> User_Support { get; set; }
        public Nullable<System.DateTime> User_Date { get; set; }
        public Nullable<int> User_Pos { get; set; }
        public Nullable<int> User_Role { get; set; }
        public Nullable<bool> User_isSendInfo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_RoleUser> tbl_RoleUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Mess> tbl_Mess { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Mod> tbl_Mod { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ModAdmin> tbl_ModAdmin { get; set; }
    }
}
