//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QCMS_BUSSINESS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Department
    {
        public int Department_ID { get; set; }
        public Nullable<int> Department_Parent { get; set; }
        public string Department_Name { get; set; }
        public string Department_Info { get; set; }
        public Nullable<bool> Department_Status { get; set; }
        public Nullable<int> Department_Pos { get; set; }
    }
}
