//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QCMS_BUSSINESS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Skin
    {
        public int Skin_ID { get; set; }
        public Nullable<int> Skintype_ID { get; set; }
        public Nullable<int> Mod_ID { get; set; }
        public string Skin_Name { get; set; }
        public string Skin_Url { get; set; }
        public string Skin_Link { get; set; }
        public Nullable<int> Skin_Width { get; set; }
        public Nullable<int> Skin_Height { get; set; }
        public Nullable<int> Skin_Pos { get; set; }
        public Nullable<int> Skin_Status { get; set; }
        public Nullable<int> lang { get; set; }
        public string Skin_Content { get; set; }
    
        public virtual tbl_Skintype tbl_Skintype { get; set; }
    }
}
