//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QCMS_BUSSINESS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Title
    {
        public int Title_ID { get; set; }
        public string Title_Name { get; set; }
        public string Title_Mod { get; set; }
        public string Title_Pos { get; set; }
        public Nullable<bool> Title_Status { get; set; }
        public Nullable<int> lang { get; set; }
    }
}
