//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QCMS_BUSSINESS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_File
    {
        public int File_ID { get; set; }
        public Nullable<int> Content_ID { get; set; }
        public string File_Name { get; set; }
        public string File_Small { get; set; }
        public string File_Larger { get; set; }
        public Nullable<bool> File_Status { get; set; }
        public Nullable<System.DateTime> File_Date { get; set; }
        public Nullable<int> File_Pos { get; set; }
    
        public virtual tbl_Content tbl_Content { get; set; }
    }
}
