//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QCMS_BUSSINESS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Contact
    {
        public int Contact_ID { get; set; }
        public string Contact_Name { get; set; }
        public string Contact_Company { get; set; }
        public string Contact_Tel { get; set; }
        public string Contact_Email { get; set; }
        public string Contact_Mobile { get; set; }
        public string Contact_Address { get; set; }
        public string Contact_Subject { get; set; }
        public string Contact_Content { get; set; }
        public Nullable<bool> Contact_Status { get; set; }
        public Nullable<System.DateTime> Contact_Date { get; set; }
    }
}
