//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QCMS_BUSSINESS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Boxtype
    {
        public int Boxtype_ID { get; set; }
        public string Boxtype_Code { get; set; }
        public string Boxtype_Name { get; set; }
        public Nullable<int> Boxtype_Limit { get; set; }
        public Nullable<bool> Boxtype_Status { get; set; }
        public Nullable<int> lang { get; set; }
    }
}
