//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QCMS_BUSSINESS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Mess
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Mess()
        {
            this.tbl_User = new HashSet<tbl_User>();
        }
    
        public int Mess_ID { get; set; }
        public string Mess_Sender { get; set; }
        public string Mess_Title { get; set; }
        public string Mess_Attach { get; set; }
        public string Mess_Content { get; set; }
        public Nullable<System.DateTime> Mess_Date { get; set; }
        public Nullable<bool> Mess_Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_User> tbl_User { get; set; }
    }
}
