//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QCMS_BUSSINESS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_OrderDetail
    {
        public int Order_ID { get; set; }
        public string MaVe { get; set; }
        public Nullable<double> UnitPrice { get; set; }
        public string Type { get; set; }
        public Nullable<int> isTimeOut { get; set; }
        public Nullable<int> isDone { get; set; }
    }
}
