//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QCMS_BUSSINESS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class vexedtEntities : DbContext
    {
        public vexedtEntities()
            : base("name=vexedtEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChuyenXe> ChuyenXes { get; set; }
        public virtual DbSet<Code> Codes { get; set; }
        public virtual DbSet<Diadiem> Diadiems { get; set; }
        public virtual DbSet<DiemDon> DiemDons { get; set; }
        public virtual DbSet<Ghe> Ghes { get; set; }
        public virtual DbSet<LangValue> LangValues { get; set; }
        public virtual DbSet<ModFLD> ModFLDs { get; set; }
        public virtual DbSet<NhaXe> NhaXes { get; set; }
        public virtual DbSet<QuanHuyen> QuanHuyens { get; set; }
        public virtual DbSet<SoDienThoai> SoDienThoais { get; set; }
        public virtual DbSet<tbl_Box> tbl_Box { get; set; }
        public virtual DbSet<tbl_Boxtype> tbl_Boxtype { get; set; }
        public virtual DbSet<tbl_Comment> tbl_Comment { get; set; }
        public virtual DbSet<tbl_Config> tbl_Config { get; set; }
        public virtual DbSet<tbl_Contact> tbl_Contact { get; set; }
        public virtual DbSet<tbl_Content> tbl_Content { get; set; }
        public virtual DbSet<tbl_Department> tbl_Department { get; set; }
        public virtual DbSet<tbl_File> tbl_File { get; set; }
        public virtual DbSet<tbl_Log> tbl_Log { get; set; }
        public virtual DbSet<tbl_Mess> tbl_Mess { get; set; }
        public virtual DbSet<tbl_Mod> tbl_Mod { get; set; }
        public virtual DbSet<tbl_ModAdmin> tbl_ModAdmin { get; set; }
        public virtual DbSet<tbl_Modtype> tbl_Modtype { get; set; }
        public virtual DbSet<tbl_ModUserMenu> tbl_ModUserMenu { get; set; }
        public virtual DbSet<tbl_Order> tbl_Order { get; set; }
        public virtual DbSet<tbl_OrderDetail> tbl_OrderDetail { get; set; }
        public virtual DbSet<tbl_Other> tbl_Other { get; set; }
        public virtual DbSet<tbl_Role> tbl_Role { get; set; }
        public virtual DbSet<tbl_RoleUser> tbl_RoleUser { get; set; }
        public virtual DbSet<tbl_Skin> tbl_Skin { get; set; }
        public virtual DbSet<tbl_Skintype> tbl_Skintype { get; set; }
        public virtual DbSet<tbl_Tag> tbl_Tag { get; set; }
        public virtual DbSet<tbl_Title> tbl_Title { get; set; }
        public virtual DbSet<tbl_User> tbl_User { get; set; }
        public virtual DbSet<tblImage> tblImages { get; set; }
        public virtual DbSet<TinhThanh> TinhThanhs { get; set; }
        public virtual DbSet<TuyenDuong> TuyenDuongs { get; set; }
        public virtual DbSet<GiaoDich> GiaoDiches { get; set; }
        public virtual DbSet<Hangxe> Hangxes { get; set; }
        public virtual DbSet<ModBtn> ModBtns { get; set; }
        public virtual DbSet<tbl_PhuongThucThanhToan> tbl_PhuongThucThanhToan { get; set; }
        public virtual DbSet<tbl_PromoteCode> tbl_PromoteCode { get; set; }
        public virtual DbSet<Xe> Xes { get; set; }
        public virtual DbSet<RequestTravel> RequestTravels { get; set; }
        public virtual DbSet<tbl_Member> tbl_Member { get; set; }
    
        public virtual int Content_search(string pagesize, string gotopage, string fields, string where_text, string order_text)
        {
            var pagesizeParameter = pagesize != null ?
                new ObjectParameter("pagesize", pagesize) :
                new ObjectParameter("pagesize", typeof(string));
    
            var gotopageParameter = gotopage != null ?
                new ObjectParameter("gotopage", gotopage) :
                new ObjectParameter("gotopage", typeof(string));
    
            var fieldsParameter = fields != null ?
                new ObjectParameter("Fields", fields) :
                new ObjectParameter("Fields", typeof(string));
    
            var where_textParameter = where_text != null ?
                new ObjectParameter("where_text", where_text) :
                new ObjectParameter("where_text", typeof(string));
    
            var order_textParameter = order_text != null ?
                new ObjectParameter("order_text", order_text) :
                new ObjectParameter("order_text", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Content_search", pagesizeParameter, gotopageParameter, fieldsParameter, where_textParameter, order_textParameter);
        }
    
        public virtual int DELHANGXE(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DELHANGXE", idParameter);
        }
    
        public virtual int SP_DELXE(Nullable<int> maxe)
        {
            var maxeParameter = maxe.HasValue ?
                new ObjectParameter("Maxe", maxe) :
                new ObjectParameter("Maxe", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELXE", maxeParameter);
        }
    
        public virtual ObjectResult<SP_GETALLHANGXE_Result> SP_GETALLHANGXE()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GETALLHANGXE_Result>("SP_GETALLHANGXE");
        }
    
        public virtual ObjectResult<SP_GETALLNHAXE_Result> SP_GETALLNHAXE()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GETALLNHAXE_Result>("SP_GETALLNHAXE");
        }
    
        public virtual ObjectResult<Sp_GetAllXe_Result> Sp_GetAllXe()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_GetAllXe_Result>("Sp_GetAllXe");
        }
    
        public virtual int SP_INSERTHANGXE(string name, string desc, Nullable<bool> status)
        {
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var descParameter = desc != null ?
                new ObjectParameter("Desc", desc) :
                new ObjectParameter("Desc", typeof(string));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_INSERTHANGXE", nameParameter, descParameter, statusParameter);
        }
    
        public virtual int SP_INSERTXE(string bienso, string tenxe, Nullable<int> nhaxe, string gioithieungan, string gioithieuchitiet, Nullable<bool> daxoa, Nullable<int> tongSoGhe, Nullable<int> hangxe)
        {
            var biensoParameter = bienso != null ?
                new ObjectParameter("Bienso", bienso) :
                new ObjectParameter("Bienso", typeof(string));
    
            var tenxeParameter = tenxe != null ?
                new ObjectParameter("Tenxe", tenxe) :
                new ObjectParameter("Tenxe", typeof(string));
    
            var nhaxeParameter = nhaxe.HasValue ?
                new ObjectParameter("Nhaxe", nhaxe) :
                new ObjectParameter("Nhaxe", typeof(int));
    
            var gioithieunganParameter = gioithieungan != null ?
                new ObjectParameter("Gioithieungan", gioithieungan) :
                new ObjectParameter("Gioithieungan", typeof(string));
    
            var gioithieuchitietParameter = gioithieuchitiet != null ?
                new ObjectParameter("Gioithieuchitiet", gioithieuchitiet) :
                new ObjectParameter("Gioithieuchitiet", typeof(string));
    
            var daxoaParameter = daxoa.HasValue ?
                new ObjectParameter("Daxoa", daxoa) :
                new ObjectParameter("Daxoa", typeof(bool));
    
            var tongSoGheParameter = tongSoGhe.HasValue ?
                new ObjectParameter("TongSoGhe", tongSoGhe) :
                new ObjectParameter("TongSoGhe", typeof(int));
    
            var hangxeParameter = hangxe.HasValue ?
                new ObjectParameter("Hangxe", hangxe) :
                new ObjectParameter("Hangxe", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_INSERTXE", biensoParameter, tenxeParameter, nhaxeParameter, gioithieunganParameter, gioithieuchitietParameter, daxoaParameter, tongSoGheParameter, hangxeParameter);
        }
    
        public virtual ObjectResult<SP_SELECTALLHANGXE_Result> SP_SELECTALLHANGXE()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SELECTALLHANGXE_Result>("SP_SELECTALLHANGXE");
        }
    
        public virtual int SP_UPDATEXE(Nullable<int> maxe, string bienso, string tenxe, Nullable<int> nhaxe, string gioithieungan, string gioithieuchitiet, Nullable<bool> daxoa, Nullable<int> tongSoGhe, Nullable<int> hangxe)
        {
            var maxeParameter = maxe.HasValue ?
                new ObjectParameter("Maxe", maxe) :
                new ObjectParameter("Maxe", typeof(int));
    
            var biensoParameter = bienso != null ?
                new ObjectParameter("Bienso", bienso) :
                new ObjectParameter("Bienso", typeof(string));
    
            var tenxeParameter = tenxe != null ?
                new ObjectParameter("Tenxe", tenxe) :
                new ObjectParameter("Tenxe", typeof(string));
    
            var nhaxeParameter = nhaxe.HasValue ?
                new ObjectParameter("Nhaxe", nhaxe) :
                new ObjectParameter("Nhaxe", typeof(int));
    
            var gioithieunganParameter = gioithieungan != null ?
                new ObjectParameter("Gioithieungan", gioithieungan) :
                new ObjectParameter("Gioithieungan", typeof(string));
    
            var gioithieuchitietParameter = gioithieuchitiet != null ?
                new ObjectParameter("Gioithieuchitiet", gioithieuchitiet) :
                new ObjectParameter("Gioithieuchitiet", typeof(string));
    
            var daxoaParameter = daxoa.HasValue ?
                new ObjectParameter("Daxoa", daxoa) :
                new ObjectParameter("Daxoa", typeof(bool));
    
            var tongSoGheParameter = tongSoGhe.HasValue ?
                new ObjectParameter("TongSoGhe", tongSoGhe) :
                new ObjectParameter("TongSoGhe", typeof(int));
    
            var hangxeParameter = hangxe.HasValue ?
                new ObjectParameter("Hangxe", hangxe) :
                new ObjectParameter("Hangxe", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UPDATEXE", maxeParameter, biensoParameter, tenxeParameter, nhaxeParameter, gioithieunganParameter, gioithieuchitietParameter, daxoaParameter, tongSoGheParameter, hangxeParameter);
        }
    
        public virtual ObjectResult<SP_CCB_XE_Result> SP_CCB_XE()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_CCB_XE_Result>("SP_CCB_XE");
        }
    
        public virtual int SP_DELTINH(Nullable<int> maTinh)
        {
            var maTinhParameter = maTinh.HasValue ?
                new ObjectParameter("MaTinh", maTinh) :
                new ObjectParameter("MaTinh", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELTINH", maTinhParameter);
        }
    
        public virtual ObjectResult<SP_GETALLTINH_Result> SP_GETALLTINH()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GETALLTINH_Result>("SP_GETALLTINH");
        }
    
        public virtual int SP_INSERTCHUYENXE(Nullable<int> machuyenxe, Nullable<System.DateTime> ngaydi, string giokhoihanh, string thoigiandukien, Nullable<int> maXe, string mota, string chitiet, Nullable<int> tuyenDuong, string diemdi, string diemden, Nullable<int> trangThai, Nullable<double> giaVIP, Nullable<double> giaThuong, Nullable<int> tongVe, Nullable<int> veThuongConLai, string sDT, Nullable<int> khuyenMai, string loTrinh, Nullable<int> tongSoVeVIP, Nullable<int> tongSoVeThuong, Nullable<int> veVipConLai)
        {
            var machuyenxeParameter = machuyenxe.HasValue ?
                new ObjectParameter("Machuyenxe", machuyenxe) :
                new ObjectParameter("Machuyenxe", typeof(int));
    
            var ngaydiParameter = ngaydi.HasValue ?
                new ObjectParameter("Ngaydi", ngaydi) :
                new ObjectParameter("Ngaydi", typeof(System.DateTime));
    
            var giokhoihanhParameter = giokhoihanh != null ?
                new ObjectParameter("Giokhoihanh", giokhoihanh) :
                new ObjectParameter("Giokhoihanh", typeof(string));
    
            var thoigiandukienParameter = thoigiandukien != null ?
                new ObjectParameter("Thoigiandukien", thoigiandukien) :
                new ObjectParameter("Thoigiandukien", typeof(string));
    
            var maXeParameter = maXe.HasValue ?
                new ObjectParameter("MaXe", maXe) :
                new ObjectParameter("MaXe", typeof(int));
    
            var motaParameter = mota != null ?
                new ObjectParameter("Mota", mota) :
                new ObjectParameter("Mota", typeof(string));
    
            var chitietParameter = chitiet != null ?
                new ObjectParameter("Chitiet", chitiet) :
                new ObjectParameter("Chitiet", typeof(string));
    
            var tuyenDuongParameter = tuyenDuong.HasValue ?
                new ObjectParameter("TuyenDuong", tuyenDuong) :
                new ObjectParameter("TuyenDuong", typeof(int));
    
            var diemdiParameter = diemdi != null ?
                new ObjectParameter("Diemdi", diemdi) :
                new ObjectParameter("Diemdi", typeof(string));
    
            var diemdenParameter = diemden != null ?
                new ObjectParameter("Diemden", diemden) :
                new ObjectParameter("Diemden", typeof(string));
    
            var trangThaiParameter = trangThai.HasValue ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(int));
    
            var giaVIPParameter = giaVIP.HasValue ?
                new ObjectParameter("GiaVIP", giaVIP) :
                new ObjectParameter("GiaVIP", typeof(double));
    
            var giaThuongParameter = giaThuong.HasValue ?
                new ObjectParameter("GiaThuong", giaThuong) :
                new ObjectParameter("GiaThuong", typeof(double));
    
            var tongVeParameter = tongVe.HasValue ?
                new ObjectParameter("TongVe", tongVe) :
                new ObjectParameter("TongVe", typeof(int));
    
            var veThuongConLaiParameter = veThuongConLai.HasValue ?
                new ObjectParameter("VeThuongConLai", veThuongConLai) :
                new ObjectParameter("VeThuongConLai", typeof(int));
    
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            var khuyenMaiParameter = khuyenMai.HasValue ?
                new ObjectParameter("KhuyenMai", khuyenMai) :
                new ObjectParameter("KhuyenMai", typeof(int));
    
            var loTrinhParameter = loTrinh != null ?
                new ObjectParameter("LoTrinh", loTrinh) :
                new ObjectParameter("LoTrinh", typeof(string));
    
            var tongSoVeVIPParameter = tongSoVeVIP.HasValue ?
                new ObjectParameter("TongSoVeVIP", tongSoVeVIP) :
                new ObjectParameter("TongSoVeVIP", typeof(int));
    
            var tongSoVeThuongParameter = tongSoVeThuong.HasValue ?
                new ObjectParameter("TongSoVeThuong", tongSoVeThuong) :
                new ObjectParameter("TongSoVeThuong", typeof(int));
    
            var veVipConLaiParameter = veVipConLai.HasValue ?
                new ObjectParameter("VeVipConLai", veVipConLai) :
                new ObjectParameter("VeVipConLai", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_INSERTCHUYENXE", machuyenxeParameter, ngaydiParameter, giokhoihanhParameter, thoigiandukienParameter, maXeParameter, motaParameter, chitietParameter, tuyenDuongParameter, diemdiParameter, diemdenParameter, trangThaiParameter, giaVIPParameter, giaThuongParameter, tongVeParameter, veThuongConLaiParameter, sDTParameter, khuyenMaiParameter, loTrinhParameter, tongSoVeVIPParameter, tongSoVeThuongParameter, veVipConLaiParameter);
        }
    
        public virtual int SP_INSERTTINH(string tenTinh)
        {
            var tenTinhParameter = tenTinh != null ?
                new ObjectParameter("TenTinh", tenTinh) :
                new ObjectParameter("TenTinh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_INSERTTINH", tenTinhParameter);
        }
    
        public virtual ObjectResult<SP_SELECTCHUYENXEBYID_Result> SP_SELECTCHUYENXEBYID(Nullable<int> maChuyenXe)
        {
            var maChuyenXeParameter = maChuyenXe.HasValue ?
                new ObjectParameter("MaChuyenXe", maChuyenXe) :
                new ObjectParameter("MaChuyenXe", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SELECTCHUYENXEBYID_Result>("SP_SELECTCHUYENXEBYID", maChuyenXeParameter);
        }
    
        public virtual ObjectResult<SP_SELECTHANGXEBYID_Result> SP_SELECTHANGXEBYID(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SELECTHANGXEBYID_Result>("SP_SELECTHANGXEBYID", iDParameter);
        }
    
        public virtual ObjectResult<SP_SELECTTINHBYID_Result> SP_SELECTTINHBYID(Nullable<int> maTinh)
        {
            var maTinhParameter = maTinh.HasValue ?
                new ObjectParameter("MaTinh", maTinh) :
                new ObjectParameter("MaTinh", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SELECTTINHBYID_Result>("SP_SELECTTINHBYID", maTinhParameter);
        }
    
        public virtual ObjectResult<SP_SELECTXEBYID_Result> SP_SELECTXEBYID(Nullable<int> maxe)
        {
            var maxeParameter = maxe.HasValue ?
                new ObjectParameter("Maxe", maxe) :
                new ObjectParameter("Maxe", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SELECTXEBYID_Result>("SP_SELECTXEBYID", maxeParameter);
        }
    
        public virtual int SP_UPDATETINH(Nullable<int> maTinh, string tenTinh)
        {
            var maTinhParameter = maTinh.HasValue ?
                new ObjectParameter("MaTinh", maTinh) :
                new ObjectParameter("MaTinh", typeof(int));
    
            var tenTinhParameter = tenTinh != null ?
                new ObjectParameter("TenTinh", tenTinh) :
                new ObjectParameter("TenTinh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UPDATETINH", maTinhParameter, tenTinhParameter);
        }
    
        public virtual ObjectResult<SP_ViewChuyenXe_Result> SP_ViewChuyenXe()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ViewChuyenXe_Result>("SP_ViewChuyenXe");
        }
    
        public virtual ObjectResult<SP_CCB_Huyen_FROM_Tinh_Result> SP_CCB_Huyen_FROM_Tinh(Nullable<int> matinh)
        {
            var matinhParameter = matinh.HasValue ?
                new ObjectParameter("matinh", matinh) :
                new ObjectParameter("matinh", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_CCB_Huyen_FROM_Tinh_Result>("SP_CCB_Huyen_FROM_Tinh", matinhParameter);
        }
    
        public virtual ObjectResult<SP_CCB_Tinh_Result> SP_CCB_Tinh()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_CCB_Tinh_Result>("SP_CCB_Tinh");
        }
    
        public virtual ObjectResult<SP_SELECTXEBYNHAXEID_Result> SP_SELECTXEBYNHAXEID(Nullable<int> maxe)
        {
            var maxeParameter = maxe.HasValue ?
                new ObjectParameter("Maxe", maxe) :
                new ObjectParameter("Maxe", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SELECTXEBYNHAXEID_Result>("SP_SELECTXEBYNHAXEID", maxeParameter);
        }
    }
}
